# schema version
openapi: 3.1.0

# docs
info:
  title: Nutrition Tracker API
  description: API Specification for Nutrition Tracker
  version: 0.0.1

# optional servers for public APIs

# tags are used to group the endpoints
tags:
  - name: Food Items
    description: Manage Food Items
  - name: Recipes
    description: Manage Recipes
  - name: Meals
    description: Manage Meals
  - name: Auth
    description: Manage Auth

# endpoints go here
paths:
  /api/food-items:
    description: Food Items
    summary: Food Items
    get:
      tags:
        - Food Items
      responses:
        '200':
          description: food items
          content:
            application/json:
              schema:
                type: "array"
                items:
                  $ref: '#/components/schemas/FoodItemResponse'
    post:
      tags:
        - Food Items
      requestBody:
        content:
          application/json:
            schema:
              allOf:
                - $ref: "#/components/schemas/FoodItemPostRequest"

      responses:
        201:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/FoodItemResponse"
          description:

  /api/food-items/{id}:
    get:
      tags:
        - Food Items
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/FoodItemResponse"
          description: FoodItem with the provided id
    delete:
      tags:
        - Food Items
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64

      responses:
        204:
          description: Food Item with id is deleted
        409:
          description: The food item is referenced by a meal entry or a recipe, and cannot be deleted

  /api/food-items/{id}/portions:
    post:
      tags:
        - Food Items
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        content:
          application/json:
            schema:
              allOf:
                - $ref: "#/components/schemas/FoodItemPortionPostRequest"
      responses:
        201:
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/FoodItemPortionSizeResponse"
          description: FoodItem portion added
        404:
          description: FoodItem not found

  /api/food-items/{id}/micronutrients:
    post:
      tags:
        - Food Items
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        content:
          application/json:
            schema:
              allOf:
                - $ref: "#/components/schemas/FoodItemMicronutrientPostRequest"
      responses:
        201:
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/FoodItemMicronutrientResponse"
          description: Micronutrient added
        404:
          description: FoodItem not found


  /api/meals:
    get:
      tags:
        - Meals
      parameters:
        - name: dateFrom
          in: query
          schema:
            type: string
            format: date-time
        - name: dateTo
          in: query
          schema:
            type: string
            format: date-time

      responses:
        200:
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/MealResponse"
          description: Meals in between the dates provided
    post:
      tags:
        - Meals
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/MealPostRequest"
      responses:
        201:
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MealResponse"
          description:

  /api/meals/{id}:
    get:
      tags:
        - Meals
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MealResponse"
          description: Meals with the provided id
    delete:
      tags:
        - Meals
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64

      responses:
        204:
          description: Meal with id is deleted

  /api/meals/{id}/recipe-entries:
    post:
      tags:
        - Meals
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/MealRecipeEntryPostRequest"
      responses:
        201:
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MealRecipeEntryResponse"
          description: Meals entry that was added

  /api/meals/{id}/macronutrient-entries:
    post:
      description: Adds macronutrients as a meal entry
      tags:
        - Meals
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/MealMacronutrientEntryPostRequest"
      responses:
        201:
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MealMacronutrientEntryResponse"
          description: Meals entry that was added

  /api/meals/{id}/food-item-entries:
    post:
      tags:
        - Meals
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/MealFoodItemEntryPostRequest"
      responses:
        201:
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MealFoodItemEntryResponse"
          description: Meals entry that was added
  /api/meals/{mealId}/entries/{entryId}:
    delete:
      tags:
        - Meals
      parameters:
        - name: mealId
          in: path
          required: true
          schema:
            type: integer
            format: int64
        - name: entryId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        204:
          description: Meals entry is deleted


  /api/recipes:
    get:
      tags:
        - Recipes
      responses:
        200:
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/RecipeResponse'
          description: All recipes owned by user
    post:
      tags:
        - Recipes
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RecipePostRequest"
      responses:
        201:
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RecipeResponse"
          description: Recipe created

  /api/recipes/{id}:
    delete:
      tags:
        - Recipes
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64

      responses:
        204:
          description: Recipe with id is deleted
        409:
          description: The recipe is referenced by a meal entry and cannot be deleted

  /api/login:
    post:
      tags:
        - Auth
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'
          description: Log in the user


  /api/register:
    post:
      tags:
        - Auth
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterRequest'
      responses:
        201:
          description: Register the user



# reusable objects such as schemas, error types, request bodies
components:
  schemas:
    FoodItemResponse:
      type: object
      allOf:
        - $ref: "#/components/schemas/WithEnergy"
        - $ref: "#/components/schemas/WithId"
        - properties:
            ownerId:
              type: integer
              format: int64
            manufacturer:
              type: string
            product:
              type: string
            isPublic:
              type: boolean
            source:
              type: string
            portionSizes:
              type: array
              items:
                $ref: "#/components/schemas/FoodItemPortionSizeResponse"
            micronutrients:
              type: array
              items:
                $ref: "#/components/schemas/FoodItemMicronutrientResponse"

          required:
            - ownerId
            - manufacturer
            - product
            - isPublic
            - source

    FoodItemPostRequest:
      type: object
      allOf:
        - $ref: "#/components/schemas/WithMacronutrients"
        - properties:
            kCal:
              type: number
              format: double
            manufacturer:
              type: string
            product:
              type: string
            isPublic:
              type: boolean
          required:
            - manufacturer
            - product
            - isPublic

    MealPostRequest:
      type: object
      allOf:
        - $ref: "#/components/schemas/WithTimestamp"

    MealFoodItemEntryPostRequest:
      type: object
      allOf:
        - $ref: "#/components/schemas/WithAmount"
        - properties:
            foodItemId:
              type: integer
              format: int64
          required:
            - foodItemId

    MealRecipeEntryPostRequest:
      type: object
      allOf:
        - $ref: "#/components/schemas/WithAmount"
        - properties:
            recipeId:
              type: integer
              format: int64
          required:
            - recipeId

    MealMacronutrientEntryPostRequest:
      type: object
      allOf:
        - $ref: "#/components/schemas/WithMacronutrients"
        - properties:
            kCal:
              type: number
              format: double

    MealRecipeEntryResponse:
      type: object
      allOf:
        - $ref: "#/components/schemas/WithId"
        - $ref: "#/components/schemas/WithAmount"
        - $ref: "#/components/schemas/WithSequenceNumber"
        - properties:
            recipeId:
              type: integer
              format: int64
          required:
            - recipeId

    MealFoodItemEntryResponse:
      type: object
      allOf:
        - $ref: "#/components/schemas/WithId"
        - $ref: "#/components/schemas/WithAmount"
        - $ref: "#/components/schemas/WithSequenceNumber"
        - properties:
            foodItemId:
              type: integer
              format: int64
          required:
            - foodItemId

    MealMacronutrientEntryResponse:
      type: object
      allOf:
        - $ref: "#/components/schemas/WithId"
        - $ref: "#/components/schemas/WithEnergy"
        - $ref: "#/components/schemas/WithSequenceNumber"
        - properties: {}

    MealResponse:
      type: object
      allOf:
        - $ref: "#/components/schemas/WithId"
        - $ref: "#/components/schemas/WithTimestamp"
        - $ref: "#/components/schemas/WithSequenceNumber"
        - properties:
            foodItemEntries:
              type: array
              items:
                $ref: "#/components/schemas/MealFoodItemEntryResponse"
            recipeEntries:
              type: array
              items:
                $ref: "#/components/schemas/MealRecipeEntryResponse"
            macronutrientEntries:
              type: array
              items:
                $ref: "#/components/schemas/MealMacronutrientEntryResponse"
          required:
            - entries

    RecipePostRequest:
      type: object
      properties:
        name:
          type: string
        food-item-entries:
          type: array
          items:
            $ref: "#/components/schemas/RecipeFoodItemEntryPostRequest"
      required:
        - name
        - food-item-entries


    RecipeFoodItemEntryPostRequest:
      type: object
      allOf:
        - $ref: "#/components/schemas/WithAmount"
        - properties:
            foodItemId:
              type: integer
              format: int64
          required:
            - foodItemId

    RecipeResponse:
      type: object
      allOf:
        - $ref: "#/components/schemas/WithId"
        - properties:
            name:
              type: string
            food-item-entries:
              type: array
              items:
                $ref: "#/components/schemas/RecipeFoodItemEntryEntryResponse"
          required:
            - name
            - food-item-entries

    RecipeFoodItemEntryEntryResponse:
      type: object
      allOf:
        - $ref: "#/components/schemas/WithId"
        - $ref: "#/components/schemas/WithAmount"
        - properties:
            foodItemId:
              type: integer
              format: int64
          required:
            - foodItemId


    FoodItemPortionPostRequest:
      type: object
      allOf:
        - $ref: "#/components/schemas/WithAmount"
        - properties:
            name:
              type: string
          required:
            - name

    FoodItemMicronutrientPostRequest:
      type: object
      allOf:
        - $ref: "#/components/schemas/WithAmount"
        - properties:
            name:
              type: string
          required:
            - name

    FoodItemMicronutrientResponse:
      type: object
      allOf:
        - $ref: "#/components/schemas/WithId"
        - $ref: "#/components/schemas/WithAmount"
        - properties:
            name:
              type: string
          required:
            - name


    FoodItemPortionSizeResponse:
      type: object
      allOf:
        - $ref: "#/components/schemas/WithId"
        - $ref: "#/components/schemas/WithAmount"
        - properties:
            name:
              type: string
          required:
            - name


    WithTimestamp:
      type: object
      properties:
        timestamp:
          type: string
          format: date-time
      required:
        - timestamp

    WithId:
      type: object
      properties:
        id:
          type: integer
          format: int64
      required:
        - id

    WithAmount:
      properties:
        amount:
          type: number
          format: double
      required:
        - amount

    WithSequenceNumber:
      properties:
        sequenceNumber:
          type: integer
          format: int
      required:
        - sequenceNumber

    WithEnergy:
      type: object
      allOf:
        - $ref: "#/components/schemas/WithMacronutrients"
        - properties:
            kCal:
              type: number
              format: double
          required:
            - kCal

    WithMacronutrients:
      type: object
      properties:
        protein:
          type: number
          format: double
        carbohydrate:
          type: number
          format: double
        fat:
          type: number
          format: double
      required:
        - protein
        - carbohydrate
        - fat


    LoginResponse:
      type: object
      properties:
        token:
          type: string
        id:
          type: integer
          format: int64
      required:
        - token
        - id

    RegisterRequest:
      type: object
      allOf:
        - $ref: "#/components/schemas/WithCredentials"

    LoginRequest:
      type: object
      allOf:
        - $ref: "#/components/schemas/WithCredentials"

    WithCredentials:
      type: object
      properties:
        email:
          type: string
          example: "mail@example.com"
        password:
          type: string
          format: password
          example: "pas$w0rd"
      required:
        - email
        - password

  securitySchemes:
    bearerAuth: # arbitrary name for the security scheme
      type: http
      scheme: bearer
      bearerFormat: JWT # optional, arbitrary value for documentation purposes
