services:
  database:
    image: postgres:15-alpine
    container_name: nutrition-tracker-db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=nutrition-tracker
      - POSTGRES_PASSWORD=nutrition-tracker
    ports:
      - '127.0.0.1:5015:5432'
      - '[::1]:5015:5432'
    volumes:
      - /data/bikeservice/db:/var/lib/postgresql/data

  server:
    container_name: "nutrition-tracker-api"
    build: .
    ports:
      - "127.0.0.1:5014:80"
      - "[::1]:5014:80"
    restart: unless-stopped
    volumes:
      - /data/nutrition-tracker/log:/var/log/nutrition-tracker/
