services:
  database:
    image: postgres:15-alpine
    container_name: nutrition-tracker-db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=nutrition-tracker
      - POSTGRES_PASSWORD=nutrition-tracker
    ports:
      - '127.0.0.1:5013:5432'
      - '[::1]:5013:5432'
    volumes:
      - /data/bikeservice/db:/var/lib/postgresql/data
    networks:
      - nutrition-tracker-network

  server:
    container_name: "nutrition-tracker-api"
    build: .
    ports:
      - "127.0.0.1:5012:80"
      - "[::1]:5012:80"
    restart: unless-stopped
    volumes:
      - /data/nutrition-tracker/log:/var/log/nutrition-tracker/
    networks:
      - nutrition-tracker-network

networks:
  nutrition-tracker-network:
    enable_ipv6: true
    ipam:
      config:
        - subnet: 2001:0DB8::/64
        - subnet: 172.40.0.0/24