services:
  server:
    container_name: "nutrition-tracker-server"
    build:
      context: .
      labels: 
        - "nutrition-tracker-server"
    networks:
      - nt-net
    ports:
      - "127.0.0.1:5014:80"
      - "[::1]:5014:80"
    restart: unless-stopped
    volumes:
      - /data/nutrition-tracker/log:/var/log/nutrition-tracker/

networks:
  nt-net:
    external: true
