name: Vue Build
description: Build vue project

inputs: 
  working-directory:
    required: true
    description: "Location of package.json file"

runs: 
  using: composite
  steps:
    - name: Install
      working-directory: ${{ inputs.working-directory }}
      run: npm ci
      shell: bash

    - name: Build
      working-directory: ${{ inputs.working-directory }}
      run: npm run build
      shell: bash
