name: Setup SSH
description: Initializes SSH

inputs:
  known-hosts:
    description: "Known hosts file"
    required: true
  ssh-key:
    description: "SSH-key"
    required: true
  host:
    description: "Host to log in at"
    required: true
  user:
    description: "SSH user"
    required: true

runs:
  using: "composite"
  steps:
    - name: Create SSH directory
      run: |
        echo "Creating ~/.ssh"
        mkdir -p ~/.ssh        
      shell: bash

    - name: Install SSH config
      run: |
        echo "Installing SSH config"
        cat <<EOF > ~/.ssh/config
        Host ${INPUTS_HOST}
          User ${INPUTS_USER}
          IdentityFile ~/.ssh/key
          PasswordAuthentication no
        EOF
        chmod 600 ~/.ssh/config        
      shell: bash
      env:
        INPUTS_HOST: ${{ inputs.host }}
        INPUTS_USER: ${{ inputs.user }}

    - name: Install SSH known_hosts
      run: |
        echo "Installing known_hosts"
        echo "${INPUTS_KNOWN_HOSTS}" > ~/.ssh/known_hosts
        echo "  StrictHostKeyChecking yes" >> ~/.ssh/config        
      shell: bash
      env:
        INPUTS_KNOWN_HOSTS: ${{ inputs.known-hosts }}

    - name: Install SSH key
      run: |
        echo "Installing SSH key"
        echo "${INPUTS_SSH_KEY}" > ~/.ssh/key
        chmod 600 ~/.ssh/key        
      shell: bash
      env:
        INPUTS_SSH_KEY: ${{ inputs.ssh-key }}
      
