template: testify
packages:
  github.com/vidarandrebo/nutrition-tracker/api/internal/fooditem:
    config:
      dir: .
      filename: "fooditem_mocks.go"
      pkgname: "test"
      structname: "Mock{{.InterfaceName}}"
    interfaces:
      IRepository: {}
      IService: {}