name: "On PR Changed"

on: 
  pull_request:
    branches:
      - main

jobs:
  go:
    name: "Go"
    uses: "./.github/workflows/go.yml"

  vue:
    name: "Vue"
    uses: "./.github/workflows/vue.yml"