name: "On PR Changed"

on: 
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  zizmor:
    name: "zizmor"
    uses: "$/.github/workflows/zizmor.yml"

  go:
    name: "Go"
    uses: "$/.github/workflows/go.yml"

  vue:
    name: "Vue"
    uses: "$/.github/workflows/vue.yml"

  tag:
    permissions:
      contents: write
    name: "Tag"
    uses: "$/.github/workflows/tag.yml"

  docker:
    permissions:
      contents: write
      packages: write
    name: "Docker"
    uses: "$/.github/workflows/docker.yml"
