name: "On PR Changed"

on: 
  pull_request:
    branches:
      - main

jobs:
  go:
    name: "Go"
    uses: "./.github/workflows/go.yml"

  vue:
    name: "Vue"
    uses: "./.github/workflows/vue.yml"
    with:
      upload-artifact: true

  art:
    needs: [vue]
    runs-on: ubuntu-latest
    name: "Art"
    steps:
    - name: Store artifact
      uses: actions/download-artifact@v4
      with:
        name: "client"
        path: "./static"

    - name: LS
      run: ls static

