name: "On Push Main"

on:
  push:
    branches:
      - main

permissions: { }

concurrency:
  group: publish
  queue: max

jobs:
  go:
    name: "Go"
    uses: "$/.github/workflows/go.yml"
    with:
      upload-artifact: true

  vue:
    name: "Vue"
    uses: "$/.github/workflows/vue.yml"
    with:
      upload-artifact: true

  tag:
    permissions:
      contents: write
    name: "Tag"
    uses: "$/.github/workflows/tag.yml"

  docker:
    permissions:
      contents: write
      packages: write
    name: "Docker"
    uses: "$/.github/workflows/docker.yml"
    with:
      push: true

  publish:
    needs: [ go, vue, docker ]
    name: "Publish"
    uses: "$/.github/workflows/publish.yml"
    secrets:
      KNOWN_HOSTS: ${{secrets.KNOWN_HOSTS}}
      SSH_KEY: ${{secrets.SSH_KEY}}
      SSH_HOST: ${{secrets.SSH_HOST}}
      SSH_USERNAME: ${{secrets.SSH_USERNAME}}
