name: "On PR Merged"

on:
  push:
    branches:
      - main

permissions: { }

concurrency:
  group: publish
  queue: max

jobs:
  go:
    name: "Go"
    uses: "$/.github/workflows/go.yml"
    with:
      upload-artifact: true

  vue:
    name: "Vue"
    uses: "$/.github/workflows/vue.yml"
    with:
      upload-artifact: true


  publish:
    needs: [ go, vue ]
    name: "Publish"
    uses: "$/.github/workflows/publish.yml"
    secrets:
      KNOWN_HOSTS: ${{secrets.KNOWN_HOSTS}}
      SSH_KEY: ${{secrets.SSH_KEY}}
      SSH_HOST: ${{secrets.SSH_HOST}}
      SSH_USERNAME: ${{secrets.SSH_USERNAME}}
