name: "On PR Merged"

on: 
  pull_request:
    types:
      - closed
    branches:
      - main

permissions: {}

jobs:
  go:
    name: "Go"
    uses: "./.github/workflows/go.yml"
    with:
      upload-artifact: true

  vue:
    name: "Vue"
    uses: "./.github/workflows/vue.yml"
    with:
      upload-artifact: true


  publish:
    needs: [go, vue]
    name: "Publish"
    uses: "./.github/workflows/publish.yml"
    secrets:
      KNOWN_HOSTS: ${{secrets.KNOWN_HOSTS}}
      SSH_KEY: ${{secrets.SSH_KEY}}
      SSH_HOST: ${{secrets.SSH_HOST}}
      SSH_USERNAME: ${{secrets.SSH_USERNAME}}
