name: "On PR Changed"

on: 
  pull_request:
    branches:
      - main

permissions:

jobs:
  zizmor:
    name: "zizmor"
    uses: "./.github/workflows/zizmor.yml"

  go:
    name: "Go"
    uses: "./.github/workflows/go.yml"

  vue:
    name: "Vue"
    uses: "./.github/workflows/vue.yml"
