name: "On PR Changed"

on: 
  pull_request:
    branches:
      - main

jobs:
  go:
    name: "Go"
    uses: "./.github/workflows/go.yml"
    with:
      upload-artifact: true

  vue:
    name: "Vue"
    uses: "./.github/workflows/vue.yml"
    with:
      upload-artifact: true

  art-vue:
    needs: [vue]
    runs-on: ubuntu-latest
    name: "Art-vue"
    steps:
    - name: Store artifact
      uses: actions/download-artifact@v4
      with:
        name: "client"
        path: "./static"

    - name: LS
      run: ls static


  art-go:
    needs: [go]
    runs-on: ubuntu-latest
    name: "Art-go"
    steps:
    - name: Store artifact
      uses: actions/download-artifact@v4
      with:
        name: "api"
        path: "./bin"

    - name: LS
      run: ls bin