name: Setup SSH

on: workflow_call

runs:
  using: "composite"
  steps:
    - name: Create SSH directory
      run: |
        echo "Creating ~/.ssh"
        mkdir -p ~/.ssh        
      shell: bash

    - name: Install SSH config
      run: |
        echo "Installing SSH config"
        cat <<EOF > ~/.ssh/config
        Host ${{ secrets.SSH_HOST }}
          User ${{ secrets.SSH_USERNAME }}
          IdentityFile ~/.ssh/key
          PasswordAuthentication no
        EOF
        chmod 600 ~/.ssh/config        
      shell: bash

    - name: Install SSH known_hosts
      run: |
        echo "Installing known_hosts"
        echo "${{ secrets.KNOWN_HOSTS }}" > ~/.ssh/known_hosts
        echo "  StrictHostKeyChecking yes" >> ~/.ssh/config        
      shell: bash

    - name: Install SSH key
      run: |
        echo "Installing SSH key"
        echo "${{ secrets.SSH_KEY }}" > ~/.ssh/key
        chmod 600 ~/.ssh/key        
      shell: bash
      
