name: Vue

on: 
  workflow_call:
    inputs: 
      upload-artifact:
        default: false
        type: boolean


jobs:
  build:
    name: "Build"
    defaults:
      run:
        working-directory: "./client/"


    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
      with:
        persist-credentials: false

    - name: Install pnpm
      uses: pnpm/action-setup@903f9c1a6ebcba6cf41d87230be49611ac97822e # v6.0.3
      with:
        version: 10

    - name: Build Vue
      uses: "./.github/actions/vue-build"
      with: 
        working-directory: "./client"
        
    - name: Store artifact
      if: inputs.upload-artifact
      uses: actions/upload-artifact@v7
      with:
        name: "client"
        path: "./client/dist"


