name: Vue

on: workflow_call

jobs:
  build:
    name: "Build"
    defaults:
      run:
        working-directory: "./client/"

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Build Vue
      uses: "./.github/actions/vue-build"
      with: 
        artifact-name: "client"
        


