name: Go

on: 
  workflow_call:

jobs:
  zizmor:
    name: "zizmor"

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
      with:
        persist-credentials: false

    - name: Run zizmor 🌈
      uses: zizmorcore/zizmor-action@192e21d79ab29983730a13d1382995c2307fbcaa # v0.5.7
      with:
        advanced-security: false

